FROM node:23-alpine AS BUILDER

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build


FROM node:23-alpine

WORKDIR /app

COPY --from=BUILDER /app/node_modules /app/node_modules
COPY --from=BUILDER /app/.next /app/.next
COPY . .

EXPOSE 3000

CMD ["yarn", "dev"]